"""modify skills table add input-parameters

Revision ID: 0350c08e41a5
Revises: 7bb637385f51
Create Date: 2024-10-06 18:23:31.609668

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0350c08e41a5'
down_revision = '7bb637385f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('input_parameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'input_parameters')
    # ### end Alembic commands ###
