"""add icon in skills table

Revision ID: 691988bb2c28
Revises: 95907c126d68
Create Date: 2024-08-20 15:42:14.532973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '691988bb2c28'
down_revision = '95907c126d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'icon')
    # ### end Alembic commands ###
