"""Add language in usr table

Revision ID: 7eec3db0a685
Revises: 71194fe30706
Create Date: 2024-09-08 12:41:35.053097

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7eec3db0a685'
down_revision = '71194fe30706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
