"""Add icon in team table

Revision ID: 95907c126d68
Revises: 25f6814de666
Create Date: 2024-08-18 11:17:35.577696

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "95907c126d68"
down_revision = "25f6814de666"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team", sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "icon")
    # ### end Alembic commands ###
