"""add file type and weburl in uploads model

Revision ID: b932c4b363ff
Revises: 0350c08e41a5
Create Date: 2024-10-12 10:45:13.058867

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b932c4b363ff'
down_revision = '0350c08e41a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('upload', sa.Column('web_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('upload', sa.Column('chunk_size', sa.Integer(), nullable=False))
    op.add_column('upload', sa.Column('chunk_overlap', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'chunk_overlap')
    op.drop_column('upload', 'chunk_size')
    op.drop_column('upload', 'web_url')
    op.drop_column('upload', 'file_type')
    # ### end Alembic commands ###
