"""add modelcategory andmodelcapability in model  model

Revision ID: d467010f991b
Revises: eb3cc7d93ffc
Create Date: 2024-10-16 18:05:39.118621

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd467010f991b'
down_revision = 'eb3cc7d93ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('categories', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('models', sa.Column('capabilities', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'capabilities')
    op.drop_column('models', 'categories')
    # ### end Alembic commands ###
