"""update new model and model provider

Revision ID: ecced08285f0
Revises: 732a4b7d1ccc
Create Date: 2024-08-30 08:01:41.001788

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d997b58c3de"
down_revision = "732a4b7d1ccc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modelprovider",
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True
        ),
    )
    op.alter_column(
        "modelprovider",
        "provider_name",
        existing_type=sa.VARCHAR(length=128),
        type_=sqlmodel.sql.sqltypes.AutoString(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "modelprovider", "base_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "modelprovider", "api_key", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("modelprovider", "icon", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("modelprovider", "icon", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "modelprovider", "api_key", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "modelprovider", "base_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "modelprovider",
        "provider_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.drop_column("modelprovider", "description")
    # ### end Alembic commands ###
